POST http://localhost:3333/events
Content-Type: application/json

{
    "title": "Event name XXXX",
    "details": "Event details",
    "maximumAttendees": 1
}


### 

POST http://localhost:3333/events/d4e5c3b3-9597-4d28-9647-ee7b8a619eba/attendees
Content-Type: application/json

{
    "name": "Pedro Soares",
    "email": "pedro1@gmail.com"
}

###

GET http://localhost:3333/event/6cb25883-4bbf-49dc-a0b1-9028e6663a0b


###

GET http://localhost:3333/attendees/3/badge
